name: Build macOS Release (Universal)

on:
  push:
    tags:
      - 'v*'

env:
  FLUTTER_VERSION: '3.29.0'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - arch: intel
            flutter_arch: x64
            target: x86_64-apple-darwin
            suffix: x86_64

          - arch: arm64
            flutter_arch: arm64
            target: arm64-apple-darwin
            suffix: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
          architecture: ${{ matrix.flutter_arch }}

      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS (${{ matrix.arch }})
        run: export FLUTTER_XCODE_ARCHS=${{ matrix.suffix }} && flutter build macos --release


      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.suffix }}.dmg \
            build/macos/Build/Products/Release/${{ github.event.repository.name }}.app

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.suffix }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}